name: create-artifact

on:
  schedule:
    - cron: '0 0 * * 6' # weekly apply
  push:
    branches:
      - master

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Set Go Env
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: make
        working-directory: ./
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: blog-content
          path: ./cache.zip
