name: Create release

on:
  push:
    branches:
      - master

jobs:
  crawl-blogs:
    runs-on: ubuntu-latest
    steps: 
      uses: actions/checkout@v2
      uses: actions/setup-go@v2
      run: make
  
  create-release:
    runs-on: ubuntu-latest
    steps:
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
      uses: actions/upload-release-asset@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cache.zip
        asset_name: cache.zip
        asset_content_type: application/zip