name: Create release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps: 
      - name: crawl-blogs
        uses: actions/checkout@v2
        uses: actions/setup-go@v2
          with:
            go-version: '1.17.1'
        run: make

      - name: time_log
        run: date
          id: time_log

      - name: create-release
        uses: actions/create-release@v1
          id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.time_log.outputs.time_log }}
          tag_name: Release ${{ github.ref }}
          body_path: ${{ steps.time_log.outputs.time_log }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload-release-assets
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cache.zip
          asset_name: cache.zip
          asset_content_type: application/zip
